// license.js — Polar licence check for the CLI / container. Generated by adapters.py; do not edit by hand.
'use strict';
const https = require('https'), fs = require('fs'), path = require('path'), os = require('os');
const ORG_ID = 'a5cdf664-d8e7-4f87-8895-056717aaba17';
const BENEFIT_ID = '1525ef37-6ffb-47c3-9be2-45328caf42b0';   // s142 — this product's Polar benefit (s140 law: ask with benefit_id, or one key opens every product)
const BUY_URL = 'https://buy.polar.sh/polar_cl_cmmWDH5sYqYlHlEAy4aCkF8gPdT40c3FhYupJ1VFP22';
const SLUG = 'firmware-release-gate';
const GRACE_MS = 30 * 24 * 3600 * 1000;   // after a successful check, 30 days work offline
const RECHECK_MS = 7 * 24 * 3600 * 1000;  // re-ask Polar every 7 days (refunds / cancellations)
function storePath() { return path.join(process.env.READYSTACK_HOME || path.join(os.homedir(), '.config', 'readystack'), SLUG + '.json'); }
function load() { try { return JSON.parse(fs.readFileSync(storePath(), 'utf8')); } catch (e) { return {}; } }
function save(o) { try { fs.mkdirSync(path.dirname(storePath()), { recursive: true }); fs.writeFileSync(storePath(), JSON.stringify(o)); } catch (e) { /* read-only home: still works for this run */ } }
function validate(key) {
  return new Promise(function (resolve) {
    if (!ORG_ID) return resolve({ ok: false, offline: false });
    const body = JSON.stringify(/^[0-9a-f-]{36}$/.test(BENEFIT_ID) ? { key: key, organization_id: ORG_ID, benefit_id: BENEFIT_ID } : { key: key, organization_id: ORG_ID });
    const req = https.request({ hostname: 'api.polar.sh', path: '/v1/customer-portal/license-keys/validate', method: 'POST', timeout: 8000,
      headers: { 'content-type': 'application/json', 'polar-version': '2026-04', 'content-length': Buffer.byteLength(body) } }, function (res) {
      let buf = ''; res.on('data', function (d) { buf += d; });
      res.on('end', function () {
        if (res.statusCode !== 200) return resolve({ ok: false, offline: false });
        try { const j = JSON.parse(buf); resolve({ ok: j && (j.status === 'granted' || j.valid === true || !!j.id), offline: false }); }
        catch (e) { resolve({ ok: false, offline: false }); }
      });
    });
    req.on('timeout', function () { req.destroy(); resolve({ ok: false, offline: true }); });
    req.on('error', function () { resolve({ ok: false, offline: true }); });
    req.write(body); req.end();
  });
}
async function ensure(explicitKey) {
  const st = load();
  const key = explicitKey || process.env.READYSTACK_LICENSE || st.key;
  if (!key) return { ok: false, why: 'no_key' };
  const age = Date.now() - (st.okAt || 0);
  if (!explicitKey && st.key === key && age < RECHECK_MS) return { ok: true, cached: true };
  const r = await validate(String(key).trim());
  if (r.ok) { save({ key: String(key).trim(), okAt: Date.now() }); return { ok: true }; }
  if (r.offline && st.key === key && age < GRACE_MS) return { ok: true, offline: true };
  return { ok: false, why: r.offline ? 'offline' : 'invalid' };
}
// ★s134 — 구독 규칙 피드(층3 "바뀌면 업데이트"): 키 있는 손님만 · 7일마다 · 오프라인은 캐시. 워커 GET /api/rules/<slug>?key=
const FEED_URL = 'https://getreadystack.com/api/rules/';
function pullFeed() {
  const st = load(); const key = process.env.READYSTACK_LICENSE || st.key; const cached = st.feed || null;
  if (!key) return Promise.resolve(cached);
  if (cached && (Date.now() - (st.feedAt || 0)) < RECHECK_MS) return Promise.resolve(cached);
  return new Promise(function (resolve) {
    let req;
    try {
      req = https.get(FEED_URL + encodeURIComponent(SLUG) + '?key=' + encodeURIComponent(key), { timeout: 8000, headers: { 'user-agent': 'readystack-cli' } }, function (res) {
        let buf = ''; res.on('data', function (d) { buf += d; });
        res.on('end', function () {
          if (res.statusCode !== 200) return resolve(cached);
          try { const j = JSON.parse(buf); if (!j || !Array.isArray(j.rules)) return resolve(cached); save(Object.assign(load(), { feed: j, feedAt: Date.now() })); resolve(j); }
          catch (e) { resolve(cached); }
        });
      });
    } catch (e) { return resolve(cached); }
    req.on('timeout', function () { req.destroy(); resolve(cached); });
    req.on('error', function () { resolve(cached); });
  });
}
module.exports = { ensure, BUY_URL, storePath, pullFeed };
